# Server settings
server:
  port: 8000
  host: localhost

# Database settings
database:
  type: mysql
  host: localhost
  port: 3306
  username: myuser
  password: mypassword
  database: mydatabase

# Logging settings
logging:
  level: debug
  file: /var/log/myapp.log
